# Generated by Django 5.2.7 on 2025-11-24 23:42

import creditcards.models
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15, null=True, unique=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('candidato', 'Candidato'), ('recrutador', 'Recrutador')], default='candidato', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='recrutador',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)')], default='Solteiro(a)', max_length=15),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('OUTRO', 'Prefiro não dizer')], default='OUTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='recrutador',
            name='perfil_recrutador',
            field=models.CharField(default='padrao', max_length=100),
        ),
        migrations.AlterModelTable(
            name='candidato',
            table='candidatos',
        ),
        migrations.AlterModelTable(
            name='recrutador',
            table='recrutador',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.CharField(max_length=255)),
                ('nome_perfil', models.CharField(max_length=100)),
                ('data_nascimento_perfil', models.DateField()),
                ('curriculo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, verbose_name='Status Ativo')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recrutador')),
            ],
            options={
                'db_table': 'formapagamento',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', creditcards.models.CardNumberField(max_length=25)),
                ('nome_titular', models.CharField(max_length=100)),
                ('validade', creditcards.models.CardExpiryField()),
                ('cvv', creditcards.models.SecurityCodeField(max_length=4)),
                ('formapagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.formapagamento')),
            ],
            options={
                'db_table': 'cartao',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_serviço', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Expirado', 'Expirado')], default='Ativa', max_length=10)),
                ('formapagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapagamento')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recrutador')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('forma_pgt', models.CharField(choices=[('Cartão', 'cartão'), ('Pix', 'pix')], max_length=6)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pagamento')),
            ],
            options={
                'db_table': 'assinatura',
            },
        ),
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_chave', models.CharField(choices=[('Email', 'email'), ('Telefone', 'telefone'), ('CPF', 'cpf'), ('Aleatoria', 'aleatoria')], max_length=10)),
                ('chave', models.CharField(max_length=150)),
                ('formapagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.formapagamento')),
            ],
            options={
                'db_table': 'pix',
            },
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidato')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recrutador')),
            ],
            options={
                'db_table': 'chat_pv',
            },
        ),
        migrations.CreateModel(
            name='PerfilTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfil')),
            ],
            options={
                'db_table': 'PerfilTag',
                'unique_together': {('perfil', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contrato', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('requisitos', models.TextField()),
                ('beneficios', models.TextField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('localizacao', models.CharField(max_length=200)),
                ('data_publicacao', models.DateField()),
                ('status', models.CharField(choices=[('Ativa', 'Ativa'), ('Expirada', 'Expirada')], default='Ativa', max_length=10)),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recrutador')),
            ],
            options={
                'db_table': 'vaga',
            },
        ),
        migrations.CreateModel(
            name='VagaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaga')),
            ],
            options={
                'db_table': 'VagaTag',
                'unique_together': {('vaga', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='vaga',
            name='tags',
            field=models.ManyToManyField(related_name='vagas', through='api.VagaTag', to='api.tag'),
        ),
        migrations.CreateModel(
            name='Videochamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=255)),
                ('record', models.CharField(max_length=255)),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidato')),
                ('recrutador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recrutador')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaga')),
            ],
            options={
                'db_table': 'video_chamada',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
