# Generated by Django 5.2.7 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_managers_remove_perfil_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curriculo',
            field=models.FileField(null=True, upload_to='curriculos/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento_perfil',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome_perfil',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
