# Generated by Django 5.2.7 on 2025-12-04 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_perfil_curriculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.candidato'),
        ),
    ]
