# Generated by Django 5.2.8 on 2025-12-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_perfil_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recrutador',
            name='perfil_recrutador',
            field=models.CharField(max_length=100),
        ),
    ]
