version: "3.9"

services:
  frontend:
    build: .
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/react-vite-app
      - /react-vite-app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]